### ISSUE TITLE
Naming collision stops Building of the Project

### ISSUE THREAD

**Issue by nHiRanZ** [djchie/react-native-star-rating#5]
```
Failed to build DependencyGraph: Naming collision detected: /Users/hms-mac/research/react-native/maps/MapViewExample/node_modules/react-native-star-rating/node_modules/react-native/Libraries/vendor/react/browser/eventPlugins/TouchHistoryMath.js collides with /Users/hms-mac/research/react-native/maps/MapViewExample/node_modules/react-native/Libraries/vendor/react/browser/eventPlugins/TouchHistoryMath.js
Error: Naming collision detected: /Users/hms-mac/research/react-native/maps/MapViewExample/node_modules/react-native-star-rating/node_modules/react-native/Libraries/vendor/react/browser/eventPlugins/TouchHistoryMath.js collides with /Users/hms-mac/research/react-native/maps/MapViewExample/node_modules/react-native/Libraries/vendor/react/browser/eventPlugins/TouchHistoryMath.js
    at HasteMap._updateHasteMap (HasteMap.js:132:13)
    at HasteMap.js:103:28
    at tryCallOne (/Users/hms-mac/research/react-native/maps/MapViewExample/node_modules/promise/lib/core.js:37:12)
    at /Users/hms-mac/research/react-native/maps/MapViewExample/node_modules/promise/lib/core.js:123:15
    at flush (/Users/hms-mac/research/react-native/maps/MapViewExample/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:428:9)
    at process._tickCallback (node.js:357:13)
```

I have React-Native 0.20.0 installed.

**Comment by djchie** [comment]
I just made a fix so update to 1.0.5 and it should work. Let me know if you run into any issues.
